const axios = require('axios');
const FormData = require('form-data');

const uploadToIPFS = async (fileBuffer) => {
    try {
        console.log('Uploading to IPFS via:', process.env.IPFS_NODE_URL);

        // Create a FormData instance
        const formData = new FormData();
        formData.append('file', fileBuffer, 'file.txt'); // Add the file buffer with a name

        // Send the request to IPFS
        const response = await axios.post(`${process.env.IPFS_NODE_URL}/api/v0/add`, formData, {
            headers: {
                ...formData.getHeaders(), // Include headers generated by FormData
            },
        });

        console.log('IPFS Response:', response.data);
        return response.data.Hash; // IPFS hash
    } catch (error) {
        console.error('Error uploading to IPFS:', error.response?.data || error.message);
        throw new Error('Failed to upload to IPFS');
    }
};

module.exports = { uploadToIPFS };